export * as DuxIframe from './iframe'
export * as DuxLoading from './loading'
export * as DuxLogin from './login'
export * as DuxMain from './main.vue'
export * as DuxNotFound from './notFound'
export * as DuxNotPermission from './notPermission'
